In [1]:

import numpy as np


In [2]:
sizeofa = 256*256*2
a = np.arange(sizeofa)
a

array([     0,      1,      2, ..., 131069, 131070, 131071])

In [3]:
b=np.reshape(a,newshape=(1,1,-1,256))
b

array([[[[     0,      1,      2, ...,    253,    254,    255],
         [   256,    257,    258, ...,    509,    510,    511],
         [   512,    513,    514, ...,    765,    766,    767],
         ...,
         [130304, 130305, 130306, ..., 130557, 130558, 130559],
         [130560, 130561, 130562, ..., 130813, 130814, 130815],
         [130816, 130817, 130818, ..., 131069, 131070, 131071]]]])

In [5]:
c=np.reshape(b[:, 0, :, :], -1)

In [2]:
from utils import sort_data_implicit, plot_nd, ifft_2d, combine_coils


/home/lks/.local/lib/python3.12/site-packages/sigpy/config.py:27: UserWarning: Importing cupy.cuda.cudnn failed. For more details, see the error stack below:
libcudnn.so.8: cannot open shared object file: No such file or directory
  warnings.warn(
/home/lks/.local/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [30]:
data_ind = np.random.randn(65536*2) + 1j * np.random.randn(65536*2)
data_ind = np.reshape(data_ind, newshape=(1,2, -1,256))
data_ind.shape
                            

(1, 2, 256, 256)

In [44]:
data_ind[:,0,:,:].shape

(1, 256, 256)

In [41]:
image_ind = np.zeros_like(data_ind)
im = image_ind[0]
for s in range(2):
    im[s,:,:] = ifft_2d(data_ind[:,s,:,:])
im

array([[[-2.99695773e-03+9.59723920e-06j,
          2.32284219e-03+4.79616316e-03j,
          5.71044299e-03-1.88704270e-04j, ...,
          4.55055494e-03-2.12254969e-03j,
         -1.45009544e-04-2.89790925e-03j,
          3.01971098e-03-6.20648207e-03j],
        [-3.51782134e-03+3.03073328e-03j,
         -3.26055941e-03-5.30651826e-03j,
         -4.46668790e-03-5.10079090e-03j, ...,
         -5.98649964e-03-6.03614953e-04j,
          3.13709468e-03-6.53177839e-04j,
         -3.46089029e-03-1.97199359e-03j],
        [ 1.83255520e-03-3.34771690e-03j,
         -5.55176747e-03-3.37051654e-03j,
         -1.87090512e-03+5.16207098e-03j, ...,
          1.28126861e-03-8.69854476e-03j,
          3.49819247e-04+1.54360653e-03j,
          6.04439594e-03+2.70428756e-03j],
        ...,
        [-5.12323045e-03+1.05475713e-02j,
         -1.19160180e-03+6.89973054e-03j,
          6.19977466e-03+1.17504180e-03j, ...,
         -3.09228021e-04+2.94313628e-03j,
          1.30863712e-03+3.94890411e-04j

In [42]:
image_ind = np.zeros_like(data_ind)
ims = image_ind[0]
ims = ifft_2d(data_ind[0])
ims

array([[[-2.99695773e-03+9.59723920e-06j,
          2.32284219e-03+4.79616316e-03j,
          5.71044299e-03-1.88704270e-04j, ...,
          4.55055494e-03-2.12254969e-03j,
         -1.45009544e-04-2.89790925e-03j,
          3.01971098e-03-6.20648207e-03j],
        [-3.51782134e-03+3.03073328e-03j,
         -3.26055941e-03-5.30651826e-03j,
         -4.46668790e-03-5.10079090e-03j, ...,
         -5.98649964e-03-6.03614953e-04j,
          3.13709468e-03-6.53177839e-04j,
         -3.46089029e-03-1.97199359e-03j],
        [ 1.83255520e-03-3.34771690e-03j,
         -5.55176747e-03-3.37051654e-03j,
         -1.87090512e-03+5.16207098e-03j, ...,
          1.28126861e-03-8.69854476e-03j,
          3.49819247e-04+1.54360653e-03j,
          6.04439594e-03+2.70428756e-03j],
        ...,
        [-5.12323045e-03+1.05475713e-02j,
         -1.19160180e-03+6.89973054e-03j,
          6.19977466e-03+1.17504180e-03j, ...,
         -3.09228021e-04+2.94313628e-03j,
          1.30863712e-03+3.94890411e-04j

In [43]:
ioo = np.zeros_like(data_ind)
for s in range(2):
    ioo[0,s,:,:] = np.fft.ifftshift(np.fft.ifftn(np.fft.ifftshift(data_ind[0,s,:,:])))
iop=ioo[0]
iop

array([[[-2.99695773e-03+9.59723920e-06j,
          2.32284219e-03+4.79616316e-03j,
          5.71044299e-03-1.88704270e-04j, ...,
          4.55055494e-03-2.12254969e-03j,
         -1.45009544e-04-2.89790925e-03j,
          3.01971098e-03-6.20648207e-03j],
        [-3.51782134e-03+3.03073328e-03j,
         -3.26055941e-03-5.30651826e-03j,
         -4.46668790e-03-5.10079090e-03j, ...,
         -5.98649964e-03-6.03614953e-04j,
          3.13709468e-03-6.53177839e-04j,
         -3.46089029e-03-1.97199359e-03j],
        [ 1.83255520e-03-3.34771690e-03j,
         -5.55176747e-03-3.37051654e-03j,
         -1.87090512e-03+5.16207098e-03j, ...,
          1.28126861e-03-8.69854476e-03j,
          3.49819247e-04+1.54360653e-03j,
          6.04439594e-03+2.70428756e-03j],
        ...,
        [-5.12323045e-03+1.05475713e-02j,
         -1.19160180e-03+6.89973054e-03j,
          6.19977466e-03+1.17504180e-03j, ...,
         -3.09228021e-04+2.94313628e-03j,
          1.30863712e-03+3.94890411e-04j